# Generated by Django 3.0.3 on 2020-04-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EucationLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HomeLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('Topic', models.CharField(default='', max_length=50)),
                ('Content', models.TextField(default='', max_length=500)),
                ('Upload_date', models.DateField(auto_now_add=True)),
                ('valid_upto', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
