# Generated by Django 3.0.3 on 2020-04-02 04:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Mycustomer', '0002_mycustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomer',
            name='Lonas',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mycustomer',
            name='last_seen',
            field=models.DateField(default=datetime.datetime(2020, 4, 2, 4, 42, 15, 993116, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
