# Generated by Django 3.0.3 on 2020-04-02 04:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Mycustomer', '0003_auto_20200402_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomer',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 4, 2, 4, 43, 38, 593771, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
