# Generated by Django 3.0.3 on 2020-04-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycustomer', '0007_auto_20200402_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomer',
            name='mes',
            field=models.SmallIntegerField(default=0, max_length=3),
        ),
    ]
