# Generated by Django 3.0.3 on 2020-04-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycustomer', '0008_mycustomer_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=30)),
                ('Date', models.DateField(blank=True, null=True)),
                ('feed', models.TextField(default='', max_length=300)),
                ('Profile', models.ImageField(default='', upload_to='feedback')),
            ],
        ),
        migrations.AlterField(
            model_name='mycustomer',
            name='Profile',
            field=models.ImageField(default='media/customer/simple.jpg', upload_to='customer'),
        ),
    ]
