# Generated by Django 3.0.3 on 2020-04-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycustomer', '0010_auto_20200403_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='upload_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
