# Generated by Django 3.0.3 on 2020-04-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycustomer', '0011_auto_20200403_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updates',
            name='valid_upto',
        ),
        migrations.AddField(
            model_name='updates',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='upload_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
