# Generated by Django 3.0.3 on 2020-04-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycustomer', '0012_auto_20200403_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Profile',
            field=models.ImageField(default='', upload_to='media/feedback'),
        ),
    ]
