# Generated by Django 3.0.3 on 2020-04-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycustomer', '0016_auto_20200404_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomer',
            name='DateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
