# Generated by Django 3.0.3 on 2020-04-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycustomer', '0017_mycustomer_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeloan',
            name='id',
        ),
        migrations.AddField(
            model_name='homeloan',
            name='Area',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='homeloan',
            name='Email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='homeloan',
            name='Employ',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='homeloan',
            name='Gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='homeloan',
            name='Graduate',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='homeloan',
            name='Income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homeloan',
            name='Loan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homeloan',
            name='Married',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='homeloan',
            name='Name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='homeloan',
            name='Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homeloan',
            name='Status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='homeloan',
            name='loan_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
