# Generated by Django 3.0.3 on 2020-04-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mycustomer', '0019_auto_20200407_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeLoan',
        ),
    ]
