# Generated by Django 3.0.3 on 2020-04-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycustomer', '0026_auto_20200409_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomer',
            name='Profile',
            field=models.ImageField(default='customer/simple.jpg', upload_to='customer/'),
        ),
    ]
